name: build

on:
  push:
    branches:
      - main
  workflow_dispatch:


jobs:
  build:
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
      - run: |
          npm install
          npm run test -- --watch false --browsers ChromeHeadless
          npm run build
      - name: Configure AWS credentials
        id: creds
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::790387652718:role/ng-ui
          aws-region: us-east-2
      - run: |
          docker run --rm -e AWS_ACCESS_KEY_ID=${{ steps.creds.outputs.aws-access-key-id }} -e AWS_SECRET_ACCESS_KEY=${{ steps.creds.outputs.aws-secret-access-key }} -v ./dist/ng-ui/browser/:/output/ amazon/aws-cli s3 cp /output/ s3://ng-ui-790387652718 --recursive
