name: build

on:
  workflow_dispatch:
    inputs:
      environment:
        description: github action deployment environment
        type: string
        default: dev
        options:
          - dev
          - prod
  push:
    branches:
      - main

jobs:
  build:
    permissions:
      id-token: write
      contents: read
    uses: random-builds/gha-workflows/.github/workflows/static_js_s3_site.yaml@main
    with:
      environment: ${{ inputs.environment != null && inputs.environment || 'dev' }}
