name: build

on:
  workflow_dispatch:
    inputs:
      environment:
        description: github action deployment environment
        type: string
        default: dev
        options:
          - dev
          - prod
  push:
    branches:
      - main

jobs:
  build:
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Setup dynamic variables
        run: |
          if [[ ${{ github.event_name }} == "push" ]]; then
            echo ENVIRONMENT=dev > $GITHUB_ENV
          else
            echo ENVIRONMENT=${{ inputs.environment }} > $GITHUB_ENV
          fi
      - uses: random-builds/gh-workflows/.github/workflows/static_js_s3_site.yaml@main
        with:
          environment: ${{ env.ENVIRONMENT }}
